name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JULIA_CI: 'true'
  JULIA_NUM_THREADS: 'auto'
  OPENBLAS_NUM_THREADS: '1'
  JULIA_CPU_TARGET: 'generic;icelake-server,clone_all;znver3,clone_all'

jobs:
  execute:
    strategy:
      fail-fast: false
      matrix:
        julia-ver: ['1.10', '1.12', 'pre']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-ver }}
          show-versioninfo: 'true'
      - name: Install Julia packages
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.Registry.update()
          Pkg.add(["ModelingToolkit", "OrdinaryDiffEq", "Catalyst", "Plots"])
          Pkg.status(PKGMODE_MANIFEST)
      - name: Execute code
        run: julia test.jl
