name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JULIA_CI: 'true'
  JULIA_NUM_THREADS: 'auto'
  OPENBLAS_NUM_THREADS: '1'

jobs:
  execute:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          show-versioninfo: 'true'
      - name: Cache Julia packages
        uses: julia-actions/setup-julia@v2
      - name: Install Julia packages
        shell: julia --color=yes --project=@. {0}
        run: |
          using Pkg
          Pkg.Registry.update()
          Pkg.instantiate()
          Pkg.gc()
      - name: Execute code
        run: julia --project=@. test.jl
