name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JULIA_CI: 'true'
  JULIA_CPU_TARGET: 'generic;icelake-server,clone_all;znver3,clone_all'
  JULIA_NUM_THREADS: 'auto'
  OPENBLAS_NUM_THREADS: '1'


jobs:
  execute:
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        julia-ver: ['1.12', '~1.13.0-0']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-ver }}
          show-versioninfo: 'true'
      - name: Cache Julia packages
        uses: julia-actions/cache@v3
      - name: Install Julia packages
        shell: julia --color=yes --project=@. {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Execute code
        run: julia --project=@. test.jl
